_target_: torchvision.transforms.v2.Compose
transforms: 
    - _target_: torchvision.transforms.v2.CenterCrop
      size: 448
    - _target_: torchvision.transforms.v2.ConvertBoundingBoxFormat
      format: 'XYWH'
    - _target_: torchvision.transforms.v2.SanitizeBoundingBoxes
    - _target_: torchvision.transforms.v2.Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]