_target_: dl_toolbox.datamodules.Semcity
data_path: ${paths.data}
sup: 1
unsup: -1
batch_size_s: 8
batch_size_u: 8
steps_per_epoch: 250
bands: [1,2,3]
dataset_tf:
    _target_: dl_toolbox.transforms.Compose
    transforms: 
        - _target_: dl_toolbox.transforms.Resize
          factors: [1]
        - _target_: dl_toolbox.transforms.RandomCrop2
          size: 256
        - _target_: dl_toolbox.transforms.StretchToMinmax
          mins: [0,0,0]
          maxs: [255,255,255]
num_workers: 6
merge: main5
pin_memory: False