_target_: dl_toolbox.datamodules.Semcity
data_path: ${paths.data}
sup: 80
unsup: 0
batch_size: 4
bands: [1,2,3]
dataset_tf:
    _target_: dl_toolbox.transforms.Compose
    transforms: 
        - _target_: dl_toolbox.transforms.RandomCrop2
          size: 256
        - _target_: dl_toolbox.transforms.StretchToMinmax
          mins: [0,0,0]
          maxs: [255,255,255]
num_workers: 6
merge: main5
pin_memory: False
class_weights: null