_target_: dl_toolbox.datamodules.SemcityDatamodule
data_path: ${paths.data_dir}
sup: 80
unsup: 0
batch_size: 8
bands: [4,3,2]
dataset_tf: 
    _target_: dl_toolbox.transforms.StretchToMinmaxFromCsv
    csv: ???
    min_p: p0.0
    max_p: p99.0
    bands: ${bands}
crop_size: 256
num_workers: 6
merge: all7
pin_memory: False
class_weights: null