_target_: pytorch_lightning.Trainer
_partial_: True

default_root_dir: ${hydra:run.dir}

min_epochs: 1 # prevents early stopping
max_steps: 1000000
max_epochs: 10000
fast_dev_run: False
limit_train_batches: 1.
limit_val_batches: 1.
num_sanity_val_steps: 0
val_check_interval: 1000

accelerator: cpu
devices: 1

# mixed precision for extra speed-up
# precision: 16

# perform a validation loop every N training epochs : here see val_check_interval
check_val_every_n_epoch: null

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False
