_target_: pytorch_lightning.Trainer
_partial_: True

default_root_dir: ${paths.output_dir}

min_epochs: 1 # prevents early stopping
max_steps: 200000
max_epochs: 1000
limit_train_batches: 1.
limit_val_batches: 1.

accelerator: cpu
devices: 1

# mixed precision for extra speed-up
# precision: 16

# perform a validation loop every N training epochs
check_val_every_n_epoch: 1

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False
