_target_: dl_toolbox.datamodules.Airs
data_path: ${paths.data}
filter_path: ${paths.code}/dl_toolbox/datasets/airs/train.csv
sup: 80
unsup: 0
batch_size: 8
dataset_tf:
    _target_: dl_toolbox.transforms.Compose
    transforms: 
        - _target_: dl_toolbox.transforms.RandomCrop2
          size: 256
        - _target_: dl_toolbox.transforms.StretchToMinmax
          mins: [0,0,0]
          maxs: [255,255,255]
bands: [1, 2, 3]
crop_size: 512
num_workers: 6
merge: building
pin_memory: False
class_weights: null