defaults:
    - /transforms@to_0_1: to_0_1
    - /transforms@train_tf: crop
    - /transforms@test_tf: none

_target_: dl_toolbox.datamodules.Airs
data_path: ${paths.data}
filter_path: ${paths.data}/AIRS/train.csv
sup: 1
unsup: 1
batch_size_s: 4
batch_size_u: 4
steps_per_epoch: 250
bands: [1,2,3]
num_workers: 6
merge: building
pin_memory: False