# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog
  
job:
  chdir: True  

run:
  dir: ${paths.output_dir}/${experiment_name}/${now:%Y-%m-%d_%H%M%S}
sweep:
  dir: ${paths.output_dir}/${experiment_name}/${now:%Y-%m-%d_%H%M%S}