# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog
  
job:
  chdir: True

# output directory, generated dynamically on each run
#run:
#  dir: ${paths.output_dir}/datamodule:${datamodule.name}/${now:%Y-%m-%d_%H%M%S}
#sweep:
#  dir: ${paths.output_dir}/datamodule:${datamodule.name}/${now:%Y-%m-%d_%H%M%S}
#  subdir: ${hydra.job.num}
  

