_target_: dl_toolbox.modules.supervised.Supervised

class_weights: [0., 1., 1., 1., 1., 1.]
mixup: 0.

network:
  _target_: segmentation_models_pytorch.Unet
  _partial_: True
  encoder_name: efficientnet-b0
  encoder_weights: imagenet
  
optimizer:
  _target_: torch.optim.SGD
  _partial_: True
  lr: 0.04
  momentum: 0.9
  weight_decay: 0.0001
  
loss:
  _target_: torch.nn.CrossEntropyLoss
  _partial_: True






