_target_: torch.optim.lr_scheduler.LambdaLR
_partial_: True
lr_lambda: 
    _target_: dl_toolbox.schedulers.SwaLR
    start_lr: 1
    end_lr: 0.01
    start_swa: 100
    cycle_len: 20
    cycle_min: 0.01
    cycle_max: 0.01
    mode: lin