# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# you can replace it with "." if you want the root to be the current working directory
root_dir: /home/eh/fournip/dl_toolbox

# path to data directory
data_dir: /work/OT/ai4geo/DATA/DATASETS

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: /work/OT/ai4usr/fournip/outputs/${hydra:runtime.choices.datamodule}/${hydra:runtime.choices.module}/${now:%Y-%m-%d_%H%M%S}

# path to logging directory
log_dir: ${paths.output_dir}/logs/

# path to working directory
work_dir: ${hydra:runtime.cwd}
