defaults:
    - /transforms@train_tf: semcity/train
    - /transforms@test_tf: semcity/test
    - /transforms@val_tf: semcity/val

_target_: dl_toolbox.datamodules.Semcity
data_path: ${paths.data}
num_windows: 12
merge: main5
batch_size: 4
num_workers: 6
pin_memory: True
epoch_steps: 1000