defaults:
    - /transforms@to_0_1: none
    - /transforms@train_tf: none
    - /transforms@test_tf: none
_target_: dl_toolbox.datamodules.DigitanieAi4geo
data_path: ${paths.data}
bands: [1,2,3]
merge: main5
batch_size: 8
num_workers: 6
pin_memory: False
steps_per_epoch: 250
sup: 1
unsup: -1