defaults:
    - /transforms@train_tf: crop_d4
    - /transforms@test_tf: none
    
_target_: dl_toolbox.datamodules.Digitanie
data_path: ${paths.data}
sup: 1
unsup: -1
batch_size_s: 8
batch_size_u: 8
steps_per_epoch: 250
bands: [1,2,3]
num_workers: 6
merge: nomenc
pin_memory: False
city: TOULOUSE
norm_per_city: true