_target_: dl_toolbox.datamodules.Digitanie
data_path: ${paths.data}
bands: [1,2,3]
dataset_tf: 
    _target_: dl_toolbox.transforms.StretchToMinmaxFromCsv
    csv: ???
    min_p: p0.0
    max_p: p99.0
    bands: ${bands}
merge: main
batch_size: 8
num_workers: 6
pin_memory: False
city: ???
sup: 80
unsup: 0