defaults:
  - _self_
  - optimizer: sgd
  - /transforms@tf: crop_and_flip
  - network@network: smpunet
  - network@network2: smpunet
  - scheduler: linear
  - loss@ce_loss: ce
  - loss@dice_loss: dice

_target_: dl_toolbox.modules.CrossPseudoSupervision
alpha_ramp:
    _target_: dl_toolbox.utils.SigmoidRamp
    start: 0
    end: 50
    start_val: 0.1
    end_val: 0.1
ce_weight: 1
dice_weight: 0