defaults:
  - /optimizer: sgd
  - /scheduler: constant
  - /network: smpunet
  - /loss@ce_loss: ce
  - /loss@dice_loss: dice
  - /transforms@batch_tf: none
  - /transforms@tta: tta
  - /loss@ce_loss_u: ce
  - /transforms@weak_tf: color
  - /transforms@strong_tf: color
  - _self_

_target_: dl_toolbox.modules.Fixmatch
alpha_ramp:
    _target_: dl_toolbox.utils.ConstantRamp
    val: 0.1
ce_loss_u:
    reduction: none
weak_tf:
    bounds: [0.8, 0.8]
strong_tf:
    bounds: [0.5, 1.5]
threshold: 0.95