defaults:
  - optimizer: sgd
  - network: smpunet
  - scheduler: linear
  - loss@ce_loss: ce
  - loss@dice_loss: dice
  - /transforms@tf: d4
  - loss@ce_loss_u: ce
  - _self_

_target_: dl_toolbox.modules.Fixmatch
alpha_ramp:
    _target_: dl_toolbox.utils.SigmoidRamp
    start: 0
    end: 50
    start_val: 0.1
    end_val: 0.1
ce_weight: 1
dice_weight: 0
ce_loss_u:
    reduction: none
weak_tf:
    _target_: dl_toolbox.transforms.Compose
    transforms: 
        - _target_: dl_toolbox.transforms.Color
          bounds: [0.9, 0.9]
strong_tf:
    _target_: dl_toolbox.transforms.Compose
    transforms: 
        - _target_: dl_toolbox.transforms.Color
          bounds: [0.5, 0.5]
threshold: 0.95