defaults:
  - optimizer: sgd
  - network: smpunet
  - scheduler: linear
  - loss@ce_loss: ce
  - loss@dice_loss: dice
  - /transforms@weak_tf: color
  - /transforms@mix_tf: mixup2
  - _self_


_target_: dl_toolbox.modules.Mixmatch
alpha_ramp:
    _target_: dl_toolbox.utils.SigmoidRamp
    start: 0
    end: 50
    start_val: 0.1
    end_val: 0.1.
ce_weight: 1
dice_weight: 0
weak_tf:
    bounds: [0.9, 0.9]
temperature: 0.5