defaults:
  - optimizer: sgd
  - network: smpunet
  - scheduler: constant
  - loss@ce_loss: ce
  - loss@dice_loss: dice
  - /transforms@tf: d4
  - _self_


_target_: dl_toolbox.modules.Mixmatch
alpha_ramp:
    _target_: dl_toolbox.utils.SigmoidRamp
    start: 0
    end: 50
    start_val: 0.1
    end_val: 0.1
ce_weight: 1
dice_weight: 0
weak_tf:
    _target_: dl_toolbox.transforms.Compose
    transforms: 
        - _target_: dl_toolbox.transforms.Color
          bounds: [0.9, 0.9]
mix_tf:
    _target_: dl_toolbox.transforms.Mixup2
    alpha: 0.4
temperature: 0.5