defaults:
  - /optimizer: sgd
  - /scheduler: constant
  - /network: smpunet
  - /loss@ce_loss: ce
  - /loss@dice_loss: dice
  - /transforms@batch_tf: none
  - /transforms@tta: tta
  - /loss@ce_loss_u: ce
  - /transforms@weak_tf: color
  - /transforms@mix_tf: mixup2
  - _self_



_target_: dl_toolbox.modules.Mixmatch
alpha_ramp:
    _target_: dl_toolbox.utils.ConstantRamp
    val: 0.1
weak_tf:
    bounds: [0.8, 1.2]
temperature: 0.5