defaults:
  - _self_
  - optimizer: sgd
  - network: smpunet
  - network@teacher: smpunet
  - scheduler: linear
  - loss@ce_loss: ce
  - loss@dice_loss: dice
  - /transforms@tf: d4
  - /transforms@tta: tta


_target_: dl_toolbox.modules.MeanTeacher
alpha_ramp:
    _target_: dl_toolbox.utils.SigmoidRamp
    start: 0
    end: 50
    start_val: 0.1
    end_val: 0.1
ce_weight: 1
dice_weight: 0
consistency_aug:
    _target_: dl_toolbox.transforms.Compose
    transforms: 
        - _target_: dl_toolbox.transforms.Color
          bounds: [0.9, 0.9]
ema_ramp:
    _target_: dl_toolbox.utils.SigmoidRamp
    start: 0
    end: 10
    start_val: 0.999
    end_val: 0.999
consistency_loss:
    _target_: torch.nn.MSELoss
    reduction: mean