defaults:
  - /optimizer: sgd
  - /scheduler: constant
  - /transforms@sliding: null
  - /transforms@tta: null
  - _self_

_target_: dl_toolbox.modules.SegmenterLinear
encoder: 'vit_small_patch14_dinov2'
metric_ignore_index: null