defaults:
  - optimizer: sgd
  - network: smpunet
  - scheduler: linear
  - loss@ce_loss: ce
  - loss@dice_loss: dice
  - /transforms@tf: crop_and_flip
  - /transforms@strong_tf: color
  - _self_

_target_: dl_toolbox.modules.SelfTraining
ce_weight: 1
dice_weight: 0