defaults:
  - optimizer: sgd
  - network: smpunet
  - scheduler: step
  - loss@ce_loss: ce
  - loss@dice_loss: dice
  - /transforms@weak_tf: color
  - /transforms@strong_tf: color
  - _self_


_target_: dl_toolbox.modules.SelfTraining
ce_weight: 1
dice_weight: 0
weak_tf:
    bounds: [0.9, 0.9]
strong_tf:
    bounds: [0.5, 0.5]