defaults:
  - _self_
  - optimizer: sgd
  - scheduler: linear
  - network: smpunet
  - loss@ce_loss: ce
  - loss@dice_loss: dice

_target_: dl_toolbox.modules.Supervised
ce_weight: 1
dice_weight: 0
tf:
    _target_: dl_toolbox.transforms.RandomCrop2
    size: 256