defaults:
  - _self_
  - optimizer: sgd
  - scheduler: linear
  - network: smpunet
  - loss@ce_loss: ce
  - loss@dice_loss: dice
  - /transforms@tf: crop_d4
  - /transforms@tta: tta

_target_: dl_toolbox.modules.Supervised
ce_weight: 1
dice_weight: 0