defaults:
    - /transforms@train_tf: rellis/train
    - /transforms@test_tf: rellis/test
    - /transforms@val_tf: rellis/val

_target_: dl_toolbox.datamodules.Rellis
data_path: ${paths.data}
batch_size: 4
num_workers: 6
merge: all20
pin_memory: True
epoch_steps: 1000