defaults:
    - /transforms@train_tf: resisc/resisc_train
    - /transforms@test_tf: resisc/resisc_test

_target_: dl_toolbox.datamodules.Resisc
data_path: ${paths.data}
batch_size: 16
num_workers: 6
merge: all45
pin_memory: True