defaults:
  - /transforms@train_tf: none
  - /transforms@val_tf: none
  - /transforms@test_tf: none
  - _self_

_target_: dl_toolbox.datamodules.Flair2Pseudosup
data_path: ${paths.data}
prop: 30
batch_size: 32
bands: [1, 2, 3]
num_workers: 6
merge: hierarchical6
pin_memory: False
class_weights: null
pl_dir: /data/outputs/flair2_3_97/supervised_dummy/2023-09-05_102306/checkpoints/last_preds
thresh: 10