_target_: torchvision.transforms.v2.Compose
transforms: 
    - _target_: torchvision.transforms.v2.CenterCrop
      size: 504
    - _target_: torchvision.transforms.v2.Normalize
      mean: [0.5,0.5,0.5]
      std: [0.5,0.5,0.5]