_target_: torchvision.transforms.v2.Compose
transforms: 
    - _target_: torchvision.transforms.v2.Resize
      size: [480,480]
      antialias: True
    - _target_: torchvision.transforms.v2.RandomHorizontalFlip
      p: 0.5
    - _target_: dl_toolbox.transforms.ToFloat32
      scale: True
    - _target_: torchvision.transforms.v2.Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
