_target_: dl_toolbox.transforms.Compose
transforms: 
    - _target_: dl_toolbox.transforms.RandomCrop2
      size: 256
    - _target_: dl_toolbox.tranforms.Color
      bounds: [0.8,0.8]
    - _target_: dl_toolbox.transforms.D4
