_target_: dl_toolbox.transforms.Compose
transforms: 
    - _target_: dl_toolbox.transforms.RandomCrop2
      size: 256
    - _target_: dl_toolbox.transforms.ZeroAverageCommon
      meanval: [0.28689554, 0.32513303, 0.28389177]