_target_: torchvision.transforms.v2.Compose
transforms: 
    - _target_: torchvision.transforms.v2.RandomHorizontalFlip
      p: 0.5
    - _target_: torchvision.transforms.v2.RandomCrop
      size: 588

