_target_: dl_toolbox.transforms.Compose
transforms: 
    - _target_: dl_toolbox.transforms.D4
    - _target_: dl_toolbox.transforms.RandomResizedCrop
      size: 224
      scale: [0.5, 1]
      ratio: [0.75, 1.3]

