_target_: dl_toolbox.transforms.Compose
transforms: 
    - _target_: dl_toolbox.transforms.Resize
      sizes: [384, 448, 512, 576, 640, 704, 768]
    - _target_: dl_toolbox.transforms.D4
    - _target_: dl_toolbox.transforms.Color
      bounds: [0.7, 0.7]
    - _target_: dl_toolbox.transforms.RandomCrop2
      size: 384