_target_: dl_toolbox.datamodules.ResiscPseudosup
data_path: ${paths.data}
dataset_tf:
    _target_: dl_toolbox.transforms.Compose
    transforms: 
        - _target_: dl_toolbox.transforms.RandomCrop2
          size: 256
        - _target_: dl_toolbox.transforms.StretchToMinmax
          mins: [0,0,0]
          maxs: [255,255,255]
sup: 80
unsup: 0
batch_size: 8
num_workers: 16
merge: all45
pin_memory: False
class_weights: null
pl_dir: ???
thresh: 1000