defaults:
    - /transforms@train_tf: d4
    - /transforms@test_tf: none

_target_: dl_toolbox.datamodules.Resisc
data_path: ${paths.data}
sup: 1
unsup: -1
batch_size_s: 8
batch_size_u: 8
steps_per_epoch: 250
num_workers: 16
merge: all45
pin_memory: False