defaults:
  - /optimizer: sgd
  - /scheduler: constant
  - /network: smpunet
  - /loss@ce_loss: ce
  - /loss@dice_loss: dice
  - /transforms@batch_tf: none
  - /transforms@tta: tta
  - /transforms@norm: imagenet_norm
  - /transforms@cutmix: cutmix
  - /loss@cps_loss: ce
  - /network@network2: smpunet
  - _self_
  
_target_: dl_toolbox.modules.CrossPseudoSupervision
metric_ignore_index: null
alpha_ramp:
    _target_: dl_toolbox.utils.ConstantRamp
    val: 0.1