defaults:
  - /optimizer: sgd
  - /scheduler: constant
  - /network: smpunet
  - /loss: ce
  - /transforms@tta: null
  - /transforms@sliding: null
  - _self_

_target_: dl_toolbox.modules.Supervised
metric_ignore_index: null
one_hot: false