model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: Total loss/val # name of the logged metric which determines when model is improving
  mode: min
  save_top_k: 1
  dirpath: ${hydra:run.dir}/checkpoints
  #filename: "epoch_{epoch:03d}"
  save_last: True
  auto_insert_metric_name: False
