swa:
  #_target_: pytorch_lightning.callbacks.StochasticWeightAveraging
  _target_: dl_toolbox.callbacks.StochasticWeightAveraging
  #swa_lrs: 0.05
  swa_epoch_start: 0.8
  avg_every_n_epochs: 1
  #annealing_epochs: 10
  #annealing_strategy: cos
  avg_fn: null
  device: null