# @package _global_
experiment_name: default
# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - datamodule: resisc/resisc
  - module: base_classifier
  - callbacks:
      - model_checkpoint
      - preds_visu
      - lr_monitor
      - lora
      - finetuning
      - calibration
  - paths: qdtis056z
  - trainer: default
  - hydra: default
  - hparams_search: null

ckpt: null
seed: 1
