# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - datamodule: rellis
  - module: segmenter_linear
  - callbacks:
      - preds_writing
  - paths: qdtis056z
  - trainer: default
  - hydra: default
  - hparams_search: null

ckpt: ???
seed: 1
experiment_name: rellis
