# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - datamodule: resisc/resisc
  - module: supervised
  - callbacks:
      - model_checkpoint
      - seg_preds_visu
      - det_preds_visu
      - lr_monitor
      - lora
      - calibration
  - paths: qdtis056z
  - trainer: gpu
  - hydra: default
  - hparams_search: null

ckpt: null
seed: 1
