# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - module: supervised
  - callbacks:
      - classif_preds_writer
  - paths: qdtis056z
  - trainer: gpu
  - hydra: default

ckpt: ???