# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - datamodule: split_from_csv
  - module: supervised
  - paths: qdtis056z
  - trainer: gpu
  - hydra: default

