# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - datamodules: digitanie.yaml
  - modules: supervised.yaml
  - paths: qdtis056z.yaml
  - trainer: gpu.yaml
  - hydra: default.yaml

