# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - datamodule: resisc
  - module: supervised
  - callbacks:
      - image_visu
      - model_checkpoint
      - model_summary
      - early_stopping
  - paths: qdtis056z
  - trainer: gpu
  - hydra: default