# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - datamodule: split_from_csv
  - module: multilabel
  - callbacks:
      - confmat
      - image_visu
      - model_checkpoint
      - rich_progress_bar
      - model_summary
  - paths: qdtis056z
  - trainer: gpu
  - hydra: default
  - _self_

