# @package hydra.launcher
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
submitit_folder: ${hydra.sweep.dir}/submitit/%j
timeout_min: 720 # 24 hrs
cpus_per_task: 16
# gpus_per_node: 1
gres: gpu:1
tasks_per_node: 1
mem_gb: 120
nodes: 1
name: ${hydra.job.name}
partition: gpu_a100
account: ai4geo
qos: gpu_all
export: null
# comment: null
# constraint: null
# exclude: null
# cpus_per_gpu: null
# gpus_per_task: null
# mem_per_gpu: null
# mem_per_cpu: 8G
signal_delay_s: 120
max_num_timeout: 0
# additional_parameters: {}
array_parallelism: 5
#setup: