# @package hydra.launcher
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
submitit_folder: ${hydra.sweep.dir}/submitit/%j
timeout_min: 1440 # 24 hrs
cpus_per_task: 8
# gpus_per_node: 1
gres: gpu:1
tasks_per_node: 1
mem_gb: 128
nodes: 1
name: ${hydra.job.name}
partition: gpu
#account: null
qos: co_long_gpu
export: null
# comment: null
#constraint: v100
# exclude: null
# cpus_per_gpu: null
# gpus_per_task: null
# mem_per_gpu: null
# mem_per_cpu: 8G
signal_delay_s: 120
max_num_timeout: 0
# additional_parameters: {}
# array_parallelism: 256
setup: 
    - 'cd ""${oc.env:LOCALDIR}""'
    - 'rsync -rvl --include="img_multispec_05/" --include="semantic_05/" --include="TLS_BDSD_RGB/" --include="TLS_indMap/" --include="*.tif" --exclude="*" /scratchm/pfournie/data/SemCity-Toulouse-bench/ SemCity-Toulouse-bench/'