defaults:
    - /transforms@train_tf: coco/train
    - /transforms@test_tf: coco/test

_target_: dl_toolbox.datamodules.Coco
data_path: ${paths.data}
merge: all
batch_size: 4
num_workers: 6
pin_memory: False