defaults:
    - /transforms@train_tf: coco/train
    - /transforms@test_tf: coco/test
    - /transforms@batch_tf: coco/batch

_target_: dl_toolbox.datamodules.Coco
data_path: ${paths.data}
batch_size: 4
num_workers: 6
pin_memory: False