defaults:
    - /transforms@train_tf: flair/full

_target_: dl_toolbox.datamodules.Flair
data_path: ${paths.data}
bands: [1,2,3]
sup: 1
unsup: 0
batch_size: 4
num_workers: 6
merge: main13
pin_memory: True
test_tf: null