defaults:
  - _self_
  - datasource: digitanie
  - dataset: raster

_target_: dl_toolbox.datamodules.FromSplitfile

data_path: ${paths.data_dir}/DIGITANIE/
split: ${paths.root_dir}/dl_toolbox/datamodules/digitanie_all.csv
train_idx: [1]
val_idx: [2]
batch_size: 8
epoch_len: 200
num_workers: 0
pin_memory: False

datasrc: 

train_aug:
  _target

datasrc:
  _target_: dl_toolbox.datasrc.digitanie.Digitanie
  _partial_: True
    
dataset:
  _target_: dl_toolbox.datasets.raster.Raster
  _partial_: True
  bands: [1, 2, 3]
  crop_size: 256
  nomenclature: main

augmentations:
