defaults:
  - /transforms@train_tf: none
  - /transforms@val_tf: none
  - /transforms@test_tf: none
  - _self_

name: resisc
_target_: dl_toolbox.datamodules.DatamoduleResisc1
data_path: ${paths.data}
prop: 80
batch_size: 16
num_workers: 6
merge: all45
pin_memory: False
class_weights: null