defaults:
  - /transforms@train_tf: d4_color
  - /transforms@val_tf: none
  - /transforms@test_tf: none
  - _self_

name: resisc_semisup
_target_: dl_toolbox.datamodules.DatamoduleResisc1Semisup
data_path: ${paths.data}
prop: 80
unlabeled_prop: [0,100]
batch_size: 16
num_workers: 6
merge: all45
pin_memory: False
class_weights: null