defaults:
  - datasource: digitanie
  - dataset@train_set: raster
  - dataset@val_set: raster
  - augmentations@train_aug: flip_color
  - _self_

_target_: dl_toolbox.datamodules.SplitFromCsv

data_path: ${paths.data_dir}/DIGITANIE_v3/
csv_path: ${paths.root_dir}/dl_toolbox/datamodules/splits
csv_name: digitanie_all
batch_size: 8
epoch_len: 200
num_workers: 6
pin_memory: False