defaults:
  - _self_
  - datasource: digitanie
  - dataset@train_set: raster
  - dataset@val_set: raster
  - augmentations@train_aug: flip_color

_target_: dl_toolbox.datamodules.DigitanieFromCsv

data_path: ${paths.data_dir}/DIGITANIE/
csv_path: ${paths.root_dir}/dl_toolbox/datamodules/digitanie_all.csv
batch_size: 8
epoch_len: 200
num_workers: 8
pin_memory: False