defaults:
  - _self_
  - datasource: digitanie
  - dataset@train_set: raster
  - dataset@val_set: raster
  - augmentations@train_aug: flip_color
  - normalization: minmax_common

_target_: dl_toolbox.datamodules.SplitFromCsv

data_path: ${paths.data_dir}/DIGITANIE/
csv_path: ${paths.root_dir}/dl_toolbox/datamodules/splits/digitanie_v0_all
batch_size: 8
epoch_len: 200
num_workers: 8
pin_memory: False