defaults:
  - datasource: digitanie
  - transforms@train_tf: crop_d4_color
  - transforms@val_tf: none
  - _self_

_target_: dl_toolbox.datamodules.SplitFromCsv2

data_path: ${paths.data_dir}/DIGITANIE_v3/
csv_path: ${paths.root_dir}/dl_toolbox/datamodules/splits
csv_name: digitanie_all
merge: main
bands: [1,2,3]
crop_size: 256
batch_size: 8
epoch_len: 200
num_workers: 6
pin_memory: False