defaults:
    - /transforms@train_tf: xview/train
    - /transforms@test_tf: xview/test

_target_: dl_toolbox.datamodules.xView
merge: building
data_path: ${paths.data}
batch_size: 4
num_workers: 6
pin_memory: False