defaults:
    - /transforms@to_0_1: from_0_255
    - /transforms@train_tf: cityscapes_train
    - /transforms@test_tf: noop

_target_: dl_toolbox.datamodules.Cityscapes
data_path: ${paths.data}
sup: 16
unsup: 0
batch_size_s: 8
batch_size_u: 8
steps_per_epoch: 370
num_workers: 6
merge: all19
pin_memory: True