defaults:
  - transforms@train_tf: norm_city_crop_d4_color
  - transforms@val_tf: norm_city
  - _self_

_target_: dl_toolbox.datamodules.Cityscapes
data_path: ${paths.data}/Cityscapes/
batch_size: 8
num_workers: 6
dataset_tf:
    _target_: dl_toolbox.transforms.Compose
    transforms: 
        - _target_: dl_toolbox.transforms.RandomCrop2
          size: 256
        - _target_: dl_toolbox.transforms.StretchToMinmax
          mins: [0,0,0]
          maxs: [255,255,255]